# Configuration Netlify pour une application Nuxt 3

[build]
  # Commande à exécuter pour construire l'application
  command = "npm run build"
  
  # Répertoire contenant les fichiers statiques générés après la construction
  publish = ".output/public"

# Redirection des routes dynamiques vers index.html pour le routage côté client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables d'environnement pour la construction
[build.environment]
  NITRO_PRESET = "netlify"

# Optimisations pour les performances
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    
# Cache pour les ressources statiques
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
